version: "3.7"

services:
  dashboard:
    build:
      context: .
      args:
        SUBGRAPH_ENDPOINT: ${SUBGRAPH_ENDPOINT}
        EXPLORER_ENDPOINT: ${EXPLORER_ENDPOINT}
        EXCHANGE_ENDPOINT: ${EXCHANGE_ENDPOINT}
    ports:
      - 8080:8080
